language: android
android:
  components:
  - platform-tools
  - tools
  - build-tools-23.0.2
  - android-23
  - extra-android-m2repository
script:
- "./gradlew build"
before_install:
- openssl aes-256-cbc -K $encrypted_dfa994449d32_key -iv $encrypted_dfa994449d32_iv
  -in release.keystore.enc -out release.keystore -d
after_success:
- ./deploy.sh